# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Final.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1353, 738)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(222, 211, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 1071, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.formLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_exp = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_exp.setFont(font)
        self.label_exp.setObjectName("label_exp")
        self.horizontalLayout_2.addWidget(self.label_exp)
        self.lineEdit_exp = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_exp.setFont(font)
        self.lineEdit_exp.setObjectName("lineEdit_exp")
        self.horizontalLayout_2.addWidget(self.lineEdit_exp)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_prj = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_prj.setFont(font)
        self.label_prj.setObjectName("label_prj")
        self.horizontalLayout_2.addWidget(self.label_prj)
        self.lineEdit_prj = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_prj.setFont(font)
        self.lineEdit_prj.setObjectName("lineEdit_prj")
        self.horizontalLayout_2.addWidget(self.lineEdit_prj)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_prj_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_prj_2.setFont(font)
        self.label_prj_2.setObjectName("label_prj_2")
        self.horizontalLayout_2.addWidget(self.label_prj_2)
        self.lineEdit_prj_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_prj_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_prj_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_prj_2.setFont(font)
        self.lineEdit_prj_2.setObjectName("lineEdit_prj_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_prj_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 1071, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_data_dir = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_data_dir.setFont(font)
        self.label_data_dir.setObjectName("label_data_dir")
        self.horizontalLayout.addWidget(self.label_data_dir)
        self.lineEdit_data_dir = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_data_dir.setFont(font)
        self.lineEdit_data_dir.setObjectName("lineEdit_data_dir")
        self.horizontalLayout.addWidget(self.lineEdit_data_dir)
        self.pushButton_data_dir = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_data_dir.sizePolicy().hasHeightForWidth())
        self.pushButton_data_dir.setSizePolicy(sizePolicy)
        self.pushButton_data_dir.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_data_dir.setFont(font)
        self.pushButton_data_dir.setObjectName("pushButton_data_dir")
        self.horizontalLayout.addWidget(self.pushButton_data_dir)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(-530, 116, 1831, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(3, 1, 1301, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(769, 142, 71, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(-530, 546, 1861, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_setupselect_1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_setupselect_1.setGeometry(QtCore.QRect(1105, 20, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_setupselect_1.setFont(font)
        self.pushButton_setupselect_1.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.pushButton_setupselect_1.setObjectName("pushButton_setupselect_1")
        self.pushButton_setupselect_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_setupselect_2.setGeometry(QtCore.QRect(1105, 54, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_setupselect_2.setFont(font)
        self.pushButton_setupselect_2.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.pushButton_setupselect_2.setObjectName("pushButton_setupselect_2")
        self.pushButton_setupselect_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_setupselect_3.setGeometry(QtCore.QRect(1105, 90, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_setupselect_3.setFont(font)
        self.pushButton_setupselect_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_setupselect_3.setObjectName("pushButton_setupselect_3")
        self.comboBox_srport_8 = QtWidgets.QComboBox(self.tab)
        self.comboBox_srport_8.setGeometry(QtCore.QRect(1089, 468, 90, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_srport_8.sizePolicy().hasHeightForWidth())
        self.comboBox_srport_8.setSizePolicy(sizePolicy)
        self.comboBox_srport_8.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_srport_8.setObjectName("comboBox_srport_8")
        self.lineEdit_subid5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_subid5.setEnabled(True)
        self.lineEdit_subid5.setGeometry(QtCore.QRect(53, 342, 121, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_subid5.sizePolicy().hasHeightForWidth())
        self.lineEdit_subid5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_subid5.setFont(font)
        self.lineEdit_subid5.setDragEnabled(True)
        self.lineEdit_subid5.setObjectName("lineEdit_subid5")
        self.lineEdit_status_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_status_4.setGeometry(QtCore.QRect(836, 300, 241, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_status_4.setFont(font)
        self.lineEdit_status_4.setObjectName("lineEdit_status_4")
        self.comboBox_srport_1 = QtWidgets.QComboBox(self.tab)
        self.comboBox_srport_1.setGeometry(QtCore.QRect(1089, 174, 90, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_srport_1.sizePolicy().hasHeightForWidth())
        self.comboBox_srport_1.setSizePolicy(sizePolicy)
        self.comboBox_srport_1.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_srport_1.setObjectName("comboBox_srport_1")
        self.lineEdit_status_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_status_3.setGeometry(QtCore.QRect(836, 258, 241, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_status_3.setFont(font)
        self.lineEdit_status_3.setObjectName("lineEdit_status_3")
        self.comboBox_srport_7 = QtWidgets.QComboBox(self.tab)
        self.comboBox_srport_7.setGeometry(QtCore.QRect(1089, 426, 90, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_srport_7.sizePolicy().hasHeightForWidth())
        self.comboBox_srport_7.setSizePolicy(sizePolicy)
        self.comboBox_srport_7.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_srport_7.setObjectName("comboBox_srport_7")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(620, 142, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_var8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_var8.setGeometry(QtCore.QRect(780, 469, 41, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_var8.sizePolicy().hasHeightForWidth())
        self.pushButton_var8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_var8.setFont(font)
        self.pushButton_var8.setObjectName("pushButton_var8")
        self.pushButton_Start8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Start8.setGeometry(QtCore.QRect(525, 467, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start8.setFont(font)
        self.pushButton_Start8.setStyleSheet("background-color: rgb(28, 255, 35);")
        self.pushButton_Start8.setObjectName("pushButton_Start8")
        self.pushButton_Start7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Start7.setGeometry(QtCore.QRect(525, 425, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start7.setFont(font)
        self.pushButton_Start7.setStyleSheet("background-color: rgb(28, 255, 35);")
        self.pushButton_Start7.setObjectName("pushButton_Start7")
        self.comboBox_task1 = QtWidgets.QComboBox(self.tab)
        self.comboBox_task1.setGeometry(QtCore.QRect(179, 174, 221, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task1.sizePolicy().hasHeightForWidth())
        self.comboBox_task1.setSizePolicy(sizePolicy)
        self.comboBox_task1.setMinimumSize(QtCore.QSize(188, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_task1.setFont(font)
        self.comboBox_task1.setObjectName("comboBox_task1")
        self.pushButton_Start4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Start4.setGeometry(QtCore.QRect(525, 299, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start4.setFont(font)
        self.pushButton_Start4.setStyleSheet("background-color: rgb(28, 255, 35);")
        self.pushButton_Start4.setObjectName("pushButton_Start4")
        self.label_box8 = QtWidgets.QLabel(self.tab)
        self.label_box8.setGeometry(QtCore.QRect(1, 474, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box8.setFont(font)
        self.label_box8.setObjectName("label_box8")
        self.pushButton_Start5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Start5.setGeometry(QtCore.QRect(525, 341, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start5.setFont(font)
        self.pushButton_Start5.setStyleSheet("background-color: rgb(28, 255, 35);")
        self.pushButton_Start5.setObjectName("pushButton_Start5")
        self.pushButton_Start3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Start3.setGeometry(QtCore.QRect(525, 257, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start3.setFont(font)
        self.pushButton_Start3.setStyleSheet("background-color: rgb(28, 255, 35);")
        self.pushButton_Start3.setObjectName("pushButton_Start3")
        self.pushButton_Stop6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Stop6.setGeometry(QtCore.QRect(690, 383, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop6.setFont(font)
        self.pushButton_Stop6.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_Stop6.setObjectName("pushButton_Stop6")
        self.lineEdit_subid1 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_subid1.setEnabled(True)
        self.lineEdit_subid1.setGeometry(QtCore.QRect(53, 174, 121, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_subid1.sizePolicy().hasHeightForWidth())
        self.lineEdit_subid1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_subid1.setFont(font)
        self.lineEdit_subid1.setTabletTracking(False)
        self.lineEdit_subid1.setDragEnabled(True)
        self.lineEdit_subid1.setObjectName("lineEdit_subid1")
        self.pushButton_connect_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_connect_3.setGeometry(QtCore.QRect(1185, 257, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_connect_3.setFont(font)
        self.pushButton_connect_3.setStyleSheet("background-color: rgb(255, 209, 115);")
        self.pushButton_connect_3.setObjectName("pushButton_connect_3")
        self.label_box2 = QtWidgets.QLabel(self.tab)
        self.label_box2.setGeometry(QtCore.QRect(1, 222, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box2.setFont(font)
        self.label_box2.setObjectName("label_box2")
        self.pushButton_Stop4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Stop4.setGeometry(QtCore.QRect(690, 299, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop4.setFont(font)
        self.pushButton_Stop4.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_Stop4.setObjectName("pushButton_Stop4")
        self.lcdNumber_Timer_BOX7 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_Timer_BOX7.setGeometry(QtCore.QRect(613, 427, 64, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_Timer_BOX7.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Timer_BOX7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_Timer_BOX7.setFont(font)
        self.lcdNumber_Timer_BOX7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_Timer_BOX7.setAutoFillBackground(False)
        self.lcdNumber_Timer_BOX7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_Timer_BOX7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_Timer_BOX7.setLineWidth(0)
        self.lcdNumber_Timer_BOX7.setMidLineWidth(0)
        self.lcdNumber_Timer_BOX7.setSmallDecimalPoint(False)
        self.lcdNumber_Timer_BOX7.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Timer_BOX7.setObjectName("lcdNumber_Timer_BOX7")
        self.lineEdit_status_8 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_status_8.setGeometry(QtCore.QRect(836, 468, 241, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_status_8.setFont(font)
        self.lineEdit_status_8.setObjectName("lineEdit_status_8")
        self.lcdNumber_Timer_BOX6 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_Timer_BOX6.setGeometry(QtCore.QRect(613, 385, 64, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_Timer_BOX6.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Timer_BOX6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_Timer_BOX6.setFont(font)
        self.lcdNumber_Timer_BOX6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_Timer_BOX6.setAutoFillBackground(False)
        self.lcdNumber_Timer_BOX6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_Timer_BOX6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_Timer_BOX6.setLineWidth(0)
        self.lcdNumber_Timer_BOX6.setMidLineWidth(0)
        self.lcdNumber_Timer_BOX6.setSmallDecimalPoint(False)
        self.lcdNumber_Timer_BOX6.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Timer_BOX6.setObjectName("lcdNumber_Timer_BOX6")
        self.pushButton_connect_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_connect_4.setGeometry(QtCore.QRect(1185, 299, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_connect_4.setFont(font)
        self.pushButton_connect_4.setStyleSheet("background-color: rgb(255, 209, 115);")
        self.pushButton_connect_4.setObjectName("pushButton_connect_4")
        self.lcdNumber_Timer_BOX4 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_Timer_BOX4.setGeometry(QtCore.QRect(613, 301, 64, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_Timer_BOX4.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Timer_BOX4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_Timer_BOX4.setFont(font)
        self.lcdNumber_Timer_BOX4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_Timer_BOX4.setAutoFillBackground(False)
        self.lcdNumber_Timer_BOX4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_Timer_BOX4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_Timer_BOX4.setLineWidth(0)
        self.lcdNumber_Timer_BOX4.setMidLineWidth(0)
        self.lcdNumber_Timer_BOX4.setSmallDecimalPoint(False)
        self.lcdNumber_Timer_BOX4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Timer_BOX4.setObjectName("lcdNumber_Timer_BOX4")
        self.pushButton_connect_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_connect_6.setGeometry(QtCore.QRect(1185, 383, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_connect_6.setFont(font)
        self.pushButton_connect_6.setStyleSheet("background-color: rgb(255, 209, 115);")
        self.pushButton_connect_6.setObjectName("pushButton_connect_6")
        self.comboBox_srport_5 = QtWidgets.QComboBox(self.tab)
        self.comboBox_srport_5.setGeometry(QtCore.QRect(1089, 342, 90, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_srport_5.sizePolicy().hasHeightForWidth())
        self.comboBox_srport_5.setSizePolicy(sizePolicy)
        self.comboBox_srport_5.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_srport_5.setObjectName("comboBox_srport_5")
        self.pushButton_var3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_var3.setGeometry(QtCore.QRect(780, 259, 41, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_var3.sizePolicy().hasHeightForWidth())
        self.pushButton_var3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_var3.setFont(font)
        self.pushButton_var3.setObjectName("pushButton_var3")
        self.lineEdit_subid8 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_subid8.setEnabled(True)
        self.lineEdit_subid8.setGeometry(QtCore.QRect(53, 468, 121, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_subid8.sizePolicy().hasHeightForWidth())
        self.lineEdit_subid8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_subid8.setFont(font)
        self.lineEdit_subid8.setDragEnabled(True)
        self.lineEdit_subid8.setObjectName("lineEdit_subid8")
        self.pushButton_upload_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_upload_8.setGeometry(QtCore.QRect(415, 465, 98, 31))
        self.pushButton_upload_8.setMinimumSize(QtCore.QSize(98, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_upload_8.setFont(font)
        self.pushButton_upload_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_upload_8.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_upload_8.setObjectName("pushButton_upload_8")
        self.lcdNumber_Timer_BOX1 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_Timer_BOX1.setGeometry(QtCore.QRect(613, 175, 64, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_Timer_BOX1.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Timer_BOX1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_Timer_BOX1.setFont(font)
        self.lcdNumber_Timer_BOX1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_Timer_BOX1.setAutoFillBackground(False)
        self.lcdNumber_Timer_BOX1.setStyleSheet("selection-background-color: rgb(0, 0, 0);")
        self.lcdNumber_Timer_BOX1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_Timer_BOX1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_Timer_BOX1.setLineWidth(0)
        self.lcdNumber_Timer_BOX1.setMidLineWidth(0)
        self.lcdNumber_Timer_BOX1.setSmallDecimalPoint(False)
        self.lcdNumber_Timer_BOX1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Timer_BOX1.setObjectName("lcdNumber_Timer_BOX1")
        self.pushButton_config_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_config_3.setGeometry(QtCore.QRect(1275, 257, 41, 23))
        self.pushButton_config_3.setStyleSheet("background-color: rgb(241, 78, 255);")
        self.pushButton_config_3.setObjectName("pushButton_config_3")
        self.pushButton_Stop1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Stop1.setGeometry(QtCore.QRect(690, 173, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop1.setFont(font)
        self.pushButton_Stop1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.pushButton_Stop1.setObjectName("pushButton_Stop1")
        self.comboBox_srport_4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_srport_4.setGeometry(QtCore.QRect(1089, 300, 90, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_srport_4.sizePolicy().hasHeightForWidth())
        self.comboBox_srport_4.setSizePolicy(sizePolicy)
        self.comboBox_srport_4.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_srport_4.setObjectName("comboBox_srport_4")
        self.pushButton_Start2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Start2.setGeometry(QtCore.QRect(525, 215, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start2.setFont(font)
        self.pushButton_Start2.setStyleSheet("background-color: rgb(28, 255, 35);")
        self.pushButton_Start2.setObjectName("pushButton_Start2")
        self.pushButton_connect_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_connect_5.setGeometry(QtCore.QRect(1185, 341, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_connect_5.setFont(font)
        self.pushButton_connect_5.setStyleSheet("background-color: rgb(255, 209, 115);")
        self.pushButton_connect_5.setObjectName("pushButton_connect_5")
        self.pushButton_var6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_var6.setGeometry(QtCore.QRect(780, 385, 41, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_var6.sizePolicy().hasHeightForWidth())
        self.pushButton_var6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_var6.setFont(font)
        self.pushButton_var6.setObjectName("pushButton_var6")
        self.pushButton_config_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_config_7.setGeometry(QtCore.QRect(1275, 425, 41, 23))
        self.pushButton_config_7.setStyleSheet("background-color: rgb(241, 78, 255);")
        self.pushButton_config_7.setObjectName("pushButton_config_7")
        self.pushButton_connect_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_connect_2.setGeometry(QtCore.QRect(1185, 215, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_connect_2.setFont(font)
        self.pushButton_connect_2.setStyleSheet("background-color: rgb(255, 209, 115);")
        self.pushButton_connect_2.setObjectName("pushButton_connect_2")
        self.lcdNumber_Timer_BOX3 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_Timer_BOX3.setGeometry(QtCore.QRect(613, 259, 64, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_Timer_BOX3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Timer_BOX3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_Timer_BOX3.setFont(font)
        self.lcdNumber_Timer_BOX3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_Timer_BOX3.setAutoFillBackground(False)
        self.lcdNumber_Timer_BOX3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_Timer_BOX3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_Timer_BOX3.setLineWidth(0)
        self.lcdNumber_Timer_BOX3.setMidLineWidth(0)
        self.lcdNumber_Timer_BOX3.setSmallDecimalPoint(False)
        self.lcdNumber_Timer_BOX3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Timer_BOX3.setObjectName("lcdNumber_Timer_BOX3")
        self.pushButton_config_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_config_8.setGeometry(QtCore.QRect(1275, 467, 41, 23))
        self.pushButton_config_8.setStyleSheet("background-color: rgb(241, 78, 255);")
        self.pushButton_config_8.setObjectName("pushButton_config_8")
        self.pushButton_config_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_config_6.setGeometry(QtCore.QRect(1275, 383, 41, 23))
        self.pushButton_config_6.setStyleSheet("background-color: rgb(241, 78, 255);")
        self.pushButton_config_6.setObjectName("pushButton_config_6")
        self.lcdNumber_Timer_BOX5 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_Timer_BOX5.setGeometry(QtCore.QRect(613, 343, 64, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_Timer_BOX5.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Timer_BOX5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_Timer_BOX5.setFont(font)
        self.lcdNumber_Timer_BOX5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_Timer_BOX5.setAutoFillBackground(False)
        self.lcdNumber_Timer_BOX5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_Timer_BOX5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_Timer_BOX5.setLineWidth(0)
        self.lcdNumber_Timer_BOX5.setMidLineWidth(0)
        self.lcdNumber_Timer_BOX5.setSmallDecimalPoint(False)
        self.lcdNumber_Timer_BOX5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Timer_BOX5.setObjectName("lcdNumber_Timer_BOX5")
        self.pushButton_Start1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Start1.setGeometry(QtCore.QRect(525, 173, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start1.setFont(font)
        self.pushButton_Start1.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_Start1.setObjectName("pushButton_Start1")
        self.pushButton_Stop5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Stop5.setGeometry(QtCore.QRect(690, 341, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop5.setFont(font)
        self.pushButton_Stop5.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_Stop5.setObjectName("pushButton_Stop5")
        self.pushButton_connect_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_connect_8.setGeometry(QtCore.QRect(1185, 467, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_connect_8.setFont(font)
        self.pushButton_connect_8.setStyleSheet("background-color: rgb(255, 209, 115);")
        self.pushButton_connect_8.setObjectName("pushButton_connect_8")
        self.pushButton_connect_1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_connect_1.setGeometry(QtCore.QRect(1185, 173, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_connect_1.setFont(font)
        self.pushButton_connect_1.setStyleSheet("background-color: rgb(255, 209, 115);")
        self.pushButton_connect_1.setObjectName("pushButton_connect_1")
        self.pushButton_config_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_config_2.setGeometry(QtCore.QRect(1275, 215, 41, 23))
        self.pushButton_config_2.setStyleSheet("background-color: rgb(241, 78, 255);")
        self.pushButton_config_2.setObjectName("pushButton_config_2")
        self.lcdNumber_Timer_BOX2 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_Timer_BOX2.setGeometry(QtCore.QRect(613, 217, 64, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_Timer_BOX2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Timer_BOX2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_Timer_BOX2.setFont(font)
        self.lcdNumber_Timer_BOX2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_Timer_BOX2.setAutoFillBackground(False)
        self.lcdNumber_Timer_BOX2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_Timer_BOX2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_Timer_BOX2.setLineWidth(0)
        self.lcdNumber_Timer_BOX2.setMidLineWidth(0)
        self.lcdNumber_Timer_BOX2.setSmallDecimalPoint(False)
        self.lcdNumber_Timer_BOX2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Timer_BOX2.setObjectName("lcdNumber_Timer_BOX2")
        self.pushButton_connect_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_connect_7.setGeometry(QtCore.QRect(1185, 425, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_connect_7.setFont(font)
        self.pushButton_connect_7.setStyleSheet("background-color: rgb(255, 209, 115);")
        self.pushButton_connect_7.setObjectName("pushButton_connect_7")
        self.pushButton_config_1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_config_1.setGeometry(QtCore.QRect(1275, 173, 41, 23))
        self.pushButton_config_1.setStyleSheet("background-color: rgb(241, 78, 255);")
        self.pushButton_config_1.setObjectName("pushButton_config_1")
        self.pushButton_config_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_config_4.setGeometry(QtCore.QRect(1275, 299, 41, 23))
        self.pushButton_config_4.setStyleSheet("background-color: rgb(241, 78, 255);")
        self.pushButton_config_4.setObjectName("pushButton_config_4")
        self.pushButton_Stop2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Stop2.setGeometry(QtCore.QRect(690, 215, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop2.setFont(font)
        self.pushButton_Stop2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_Stop2.setObjectName("pushButton_Stop2")
        self.pushButton_upload_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_upload_4.setGeometry(QtCore.QRect(415, 297, 98, 31))
        self.pushButton_upload_4.setMinimumSize(QtCore.QSize(98, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_upload_4.setFont(font)
        self.pushButton_upload_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_upload_4.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_upload_4.setAutoDefault(False)
        self.pushButton_upload_4.setDefault(True)
        self.pushButton_upload_4.setFlat(False)
        self.pushButton_upload_4.setObjectName("pushButton_upload_4")
        self.pushButton_var7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_var7.setGeometry(QtCore.QRect(780, 427, 41, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_var7.sizePolicy().hasHeightForWidth())
        self.pushButton_var7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_var7.setFont(font)
        self.pushButton_var7.setObjectName("pushButton_var7")
        self.pushButton_upload_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_upload_2.setGeometry(QtCore.QRect(415, 213, 98, 31))
        self.pushButton_upload_2.setMinimumSize(QtCore.QSize(98, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_upload_2.setFont(font)
        self.pushButton_upload_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_upload_2.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_upload_2.setAutoDefault(False)
        self.pushButton_upload_2.setDefault(True)
        self.pushButton_upload_2.setFlat(False)
        self.pushButton_upload_2.setObjectName("pushButton_upload_2")
        self.pushButton_upload_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_upload_6.setGeometry(QtCore.QRect(415, 381, 98, 31))
        self.pushButton_upload_6.setMinimumSize(QtCore.QSize(98, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_upload_6.setFont(font)
        self.pushButton_upload_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_upload_6.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_upload_6.setAutoDefault(False)
        self.pushButton_upload_6.setDefault(True)
        self.pushButton_upload_6.setFlat(False)
        self.pushButton_upload_6.setObjectName("pushButton_upload_6")
        self.lcdNumber_Timer_BOX8 = QtWidgets.QLCDNumber(self.tab)
        self.lcdNumber_Timer_BOX8.setGeometry(QtCore.QRect(613, 469, 64, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_Timer_BOX8.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Timer_BOX8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_Timer_BOX8.setFont(font)
        self.lcdNumber_Timer_BOX8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_Timer_BOX8.setAutoFillBackground(False)
        self.lcdNumber_Timer_BOX8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_Timer_BOX8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_Timer_BOX8.setLineWidth(0)
        self.lcdNumber_Timer_BOX8.setMidLineWidth(0)
        self.lcdNumber_Timer_BOX8.setSmallDecimalPoint(False)
        self.lcdNumber_Timer_BOX8.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Timer_BOX8.setObjectName("lcdNumber_Timer_BOX8")
        self.pushButton_upload_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_upload_5.setGeometry(QtCore.QRect(415, 339, 98, 31))
        self.pushButton_upload_5.setMinimumSize(QtCore.QSize(98, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_upload_5.setFont(font)
        self.pushButton_upload_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_upload_5.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_upload_5.setAutoDefault(False)
        self.pushButton_upload_5.setDefault(True)
        self.pushButton_upload_5.setFlat(False)
        self.pushButton_upload_5.setObjectName("pushButton_upload_5")
        self.comboBox_srport_6 = QtWidgets.QComboBox(self.tab)
        self.comboBox_srport_6.setGeometry(QtCore.QRect(1089, 384, 90, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_srport_6.sizePolicy().hasHeightForWidth())
        self.comboBox_srport_6.setSizePolicy(sizePolicy)
        self.comboBox_srport_6.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_srport_6.setObjectName("comboBox_srport_6")
        self.lineEdit_subid6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_subid6.setEnabled(True)
        self.lineEdit_subid6.setGeometry(QtCore.QRect(53, 384, 121, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_subid6.sizePolicy().hasHeightForWidth())
        self.lineEdit_subid6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_subid6.setFont(font)
        self.lineEdit_subid6.setDragEnabled(True)
        self.lineEdit_subid6.setObjectName("lineEdit_subid6")
        self.lineEdit_status_1 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_status_1.setGeometry(QtCore.QRect(836, 174, 241, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_status_1.setFont(font)
        self.lineEdit_status_1.setObjectName("lineEdit_status_1")
        self.lineEdit_status_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_status_6.setGeometry(QtCore.QRect(836, 384, 241, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_status_6.setFont(font)
        self.lineEdit_status_6.setObjectName("lineEdit_status_6")
        self.label_box4 = QtWidgets.QLabel(self.tab)
        self.label_box4.setGeometry(QtCore.QRect(1, 306, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box4.setFont(font)
        self.label_box4.setObjectName("label_box4")
        self.label_box3 = QtWidgets.QLabel(self.tab)
        self.label_box3.setGeometry(QtCore.QRect(1, 264, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box3.setFont(font)
        self.label_box3.setObjectName("label_box3")
        self.lineEdit_subid7 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_subid7.setEnabled(True)
        self.lineEdit_subid7.setGeometry(QtCore.QRect(53, 426, 121, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_subid7.sizePolicy().hasHeightForWidth())
        self.lineEdit_subid7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_subid7.setFont(font)
        self.lineEdit_subid7.setDragEnabled(True)
        self.lineEdit_subid7.setObjectName("lineEdit_subid7")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(67, 142, 89, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_box5 = QtWidgets.QLabel(self.tab)
        self.label_box5.setGeometry(QtCore.QRect(1, 348, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box5.setFont(font)
        self.label_box5.setObjectName("label_box5")
        self.lineEdit_status_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_status_5.setGeometry(QtCore.QRect(836, 342, 241, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_status_5.setFont(font)
        self.lineEdit_status_5.setObjectName("lineEdit_status_5")
        self.lineEdit_subid2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_subid2.setEnabled(True)
        self.lineEdit_subid2.setGeometry(QtCore.QRect(53, 216, 121, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_subid2.sizePolicy().hasHeightForWidth())
        self.lineEdit_subid2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_subid2.setFont(font)
        self.lineEdit_subid2.setDragEnabled(True)
        self.lineEdit_subid2.setObjectName("lineEdit_subid2")
        self.label_box6 = QtWidgets.QLabel(self.tab)
        self.label_box6.setGeometry(QtCore.QRect(1, 390, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box6.setFont(font)
        self.label_box6.setObjectName("label_box6")
        self.lineEdit_subid3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_subid3.setEnabled(True)
        self.lineEdit_subid3.setGeometry(QtCore.QRect(53, 258, 121, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_subid3.sizePolicy().hasHeightForWidth())
        self.lineEdit_subid3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_subid3.setFont(font)
        self.lineEdit_subid3.setDragEnabled(True)
        self.lineEdit_subid3.setObjectName("lineEdit_subid3")
        self.label_box7 = QtWidgets.QLabel(self.tab)
        self.label_box7.setGeometry(QtCore.QRect(1, 432, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box7.setFont(font)
        self.label_box7.setObjectName("label_box7")
        self.label_box1 = QtWidgets.QLabel(self.tab)
        self.label_box1.setGeometry(QtCore.QRect(1, 180, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box1.setFont(font)
        self.label_box1.setObjectName("label_box1")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(928, 143, 48, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_config_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_config_5.setGeometry(QtCore.QRect(1275, 341, 41, 23))
        self.pushButton_config_5.setStyleSheet("background-color: rgb(241, 78, 255);")
        self.pushButton_config_5.setObjectName("pushButton_config_5")
        self.lineEdit_subid4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_subid4.setEnabled(True)
        self.lineEdit_subid4.setGeometry(QtCore.QRect(53, 300, 121, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_subid4.sizePolicy().hasHeightForWidth())
        self.lineEdit_subid4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_subid4.setFont(font)
        self.lineEdit_subid4.setDragEnabled(True)
        self.lineEdit_subid4.setObjectName("lineEdit_subid4")
        self.pushButton_Stop7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Stop7.setGeometry(QtCore.QRect(690, 425, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop7.setFont(font)
        self.pushButton_Stop7.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_Stop7.setObjectName("pushButton_Stop7")
        self.pushButton_Upload_all = QtWidgets.QPushButton(self.tab)
        self.pushButton_Upload_all.setGeometry(QtCore.QRect(413, 507, 101, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Upload_all.setFont(font)
        self.pushButton_Upload_all.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_Upload_all.setObjectName("pushButton_Upload_all")
        self.comboBox_task7 = QtWidgets.QComboBox(self.tab)
        self.comboBox_task7.setGeometry(QtCore.QRect(179, 426, 221, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task7.sizePolicy().hasHeightForWidth())
        self.comboBox_task7.setSizePolicy(sizePolicy)
        self.comboBox_task7.setMinimumSize(QtCore.QSize(188, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_task7.setFont(font)
        self.comboBox_task7.setObjectName("comboBox_task7")
        self.pushButton_Connect_all = QtWidgets.QPushButton(self.tab)
        self.pushButton_Connect_all.setGeometry(QtCore.QRect(1179, 507, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Connect_all.setFont(font)
        self.pushButton_Connect_all.setStyleSheet("background-color: rgb(255, 209, 115);")
        self.pushButton_Connect_all.setObjectName("pushButton_Connect_all")
        self.pushButton_var5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_var5.setGeometry(QtCore.QRect(780, 343, 41, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_var5.sizePolicy().hasHeightForWidth())
        self.pushButton_var5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_var5.setFont(font)
        self.pushButton_var5.setObjectName("pushButton_var5")
        self.comboBox_task3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_task3.setGeometry(QtCore.QRect(179, 258, 221, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task3.sizePolicy().hasHeightForWidth())
        self.comboBox_task3.setSizePolicy(sizePolicy)
        self.comboBox_task3.setMinimumSize(QtCore.QSize(188, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_task3.setFont(font)
        self.comboBox_task3.setObjectName("comboBox_task3")
        self.pushButton_var4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_var4.setGeometry(QtCore.QRect(780, 301, 41, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_var4.sizePolicy().hasHeightForWidth())
        self.pushButton_var4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_var4.setFont(font)
        self.pushButton_var4.setObjectName("pushButton_var4")
        self.comboBox_task2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_task2.setGeometry(QtCore.QRect(179, 216, 221, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task2.sizePolicy().hasHeightForWidth())
        self.comboBox_task2.setSizePolicy(sizePolicy)
        self.comboBox_task2.setMinimumSize(QtCore.QSize(188, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_task2.setFont(font)
        self.comboBox_task2.setObjectName("comboBox_task2")
        self.pushButton_Stop3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Stop3.setGeometry(QtCore.QRect(690, 257, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop3.setFont(font)
        self.pushButton_Stop3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_Stop3.setObjectName("pushButton_Stop3")
        self.comboBox_task8 = QtWidgets.QComboBox(self.tab)
        self.comboBox_task8.setGeometry(QtCore.QRect(179, 468, 221, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task8.sizePolicy().hasHeightForWidth())
        self.comboBox_task8.setSizePolicy(sizePolicy)
        self.comboBox_task8.setMinimumSize(QtCore.QSize(188, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_task8.setFont(font)
        self.comboBox_task8.setStyleSheet("")
        self.comboBox_task8.setFrame(True)
        self.comboBox_task8.setObjectName("comboBox_task8")
        self.comboBox_task6 = QtWidgets.QComboBox(self.tab)
        self.comboBox_task6.setGeometry(QtCore.QRect(179, 384, 221, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task6.sizePolicy().hasHeightForWidth())
        self.comboBox_task6.setSizePolicy(sizePolicy)
        self.comboBox_task6.setMinimumSize(QtCore.QSize(188, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_task6.setFont(font)
        self.comboBox_task6.setObjectName("comboBox_task6")
        self.comboBox_task4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_task4.setGeometry(QtCore.QRect(179, 300, 221, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task4.sizePolicy().hasHeightForWidth())
        self.comboBox_task4.setSizePolicy(sizePolicy)
        self.comboBox_task4.setMinimumSize(QtCore.QSize(188, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_task4.setFont(font)
        self.comboBox_task4.setObjectName("comboBox_task4")
        self.pushButton_upload_1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_upload_1.setGeometry(QtCore.QRect(415, 171, 98, 31))
        self.pushButton_upload_1.setMinimumSize(QtCore.QSize(98, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_upload_1.setFont(font)
        self.pushButton_upload_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_upload_1.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_upload_1.setAutoDefault(False)
        self.pushButton_upload_1.setDefault(True)
        self.pushButton_upload_1.setFlat(False)
        self.pushButton_upload_1.setObjectName("pushButton_upload_1")
        self.label_task = QtWidgets.QLabel(self.tab)
        self.label_task.setGeometry(QtCore.QRect(270, 142, 39, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_task.sizePolicy().hasHeightForWidth())
        self.label_task.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_task.setFont(font)
        self.label_task.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task.setObjectName("label_task")
        self.pushButton_upload_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_upload_7.setGeometry(QtCore.QRect(415, 423, 98, 31))
        self.pushButton_upload_7.setMinimumSize(QtCore.QSize(98, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_upload_7.setFont(font)
        self.pushButton_upload_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_upload_7.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_upload_7.setObjectName("pushButton_upload_7")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(1089, 142, 81, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_Start6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Start6.setGeometry(QtCore.QRect(525, 383, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start6.setFont(font)
        self.pushButton_Start6.setStyleSheet("background-color: rgb(28, 255, 35);")
        self.pushButton_Start6.setObjectName("pushButton_Start6")
        self.pushButton_var2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_var2.setGeometry(QtCore.QRect(780, 217, 41, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_var2.sizePolicy().hasHeightForWidth())
        self.pushButton_var2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_var2.setFont(font)
        self.pushButton_var2.setObjectName("pushButton_var2")
        self.lineEdit_status_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_status_2.setGeometry(QtCore.QRect(836, 216, 241, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_status_2.setFont(font)
        self.lineEdit_status_2.setObjectName("lineEdit_status_2")
        self.comboBox_srport_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_srport_2.setGeometry(QtCore.QRect(1089, 216, 90, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_srport_2.sizePolicy().hasHeightForWidth())
        self.comboBox_srport_2.setSizePolicy(sizePolicy)
        self.comboBox_srport_2.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_srport_2.setObjectName("comboBox_srport_2")
        self.pushButton_upload_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_upload_3.setGeometry(QtCore.QRect(415, 255, 98, 31))
        self.pushButton_upload_3.setMinimumSize(QtCore.QSize(98, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_upload_3.setFont(font)
        self.pushButton_upload_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_upload_3.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_upload_3.setAutoDefault(False)
        self.pushButton_upload_3.setDefault(True)
        self.pushButton_upload_3.setFlat(False)
        self.pushButton_upload_3.setObjectName("pushButton_upload_3")
        self.lineEdit_status_7 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_status_7.setGeometry(QtCore.QRect(836, 426, 241, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_status_7.setFont(font)
        self.lineEdit_status_7.setObjectName("lineEdit_status_7")
        self.comboBox_srport_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_srport_3.setGeometry(QtCore.QRect(1089, 258, 90, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_srport_3.sizePolicy().hasHeightForWidth())
        self.comboBox_srport_3.setSizePolicy(sizePolicy)
        self.comboBox_srport_3.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_srport_3.setObjectName("comboBox_srport_3")
        self.pushButton_var1 = QtWidgets.QPushButton(self.tab)
        self.pushButton_var1.setGeometry(QtCore.QRect(780, 175, 41, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_var1.sizePolicy().hasHeightForWidth())
        self.pushButton_var1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_var1.setFont(font)
        self.pushButton_var1.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.pushButton_var1.setObjectName("pushButton_var1")
        self.pushButton_Stop_all = QtWidgets.QPushButton(self.tab)
        self.pushButton_Stop_all.setGeometry(QtCore.QRect(690, 507, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop_all.setFont(font)
        self.pushButton_Stop_all.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_Stop_all.setObjectName("pushButton_Stop_all")
        self.comboBox_task5 = QtWidgets.QComboBox(self.tab)
        self.comboBox_task5.setGeometry(QtCore.QRect(179, 342, 221, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task5.sizePolicy().hasHeightForWidth())
        self.comboBox_task5.setSizePolicy(sizePolicy)
        self.comboBox_task5.setMinimumSize(QtCore.QSize(188, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_task5.setFont(font)
        self.comboBox_task5.setObjectName("comboBox_task5")
        self.pushButton_Stop8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_Stop8.setGeometry(QtCore.QRect(690, 467, 75, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop8.setFont(font)
        self.pushButton_Stop8.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_Stop8.setObjectName("pushButton_Stop8")
        self.pushButton_Start_all = QtWidgets.QPushButton(self.tab)
        self.pushButton_Start_all.setGeometry(QtCore.QRect(525, 507, 121, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start_all.setFont(font)
        self.pushButton_Start_all.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_Start_all.setObjectName("pushButton_Start_all")
        self.comboBox_task_multibox = QtWidgets.QComboBox(self.tab)
        self.comboBox_task_multibox.setGeometry(QtCore.QRect(20, 604, 371, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task_multibox.sizePolicy().hasHeightForWidth())
        self.comboBox_task_multibox.setSizePolicy(sizePolicy)
        self.comboBox_task_multibox.setMinimumSize(QtCore.QSize(188, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_task_multibox.setFont(font)
        self.comboBox_task_multibox.setStyleSheet("")
        self.comboBox_task_multibox.setFrame(True)
        self.comboBox_task_multibox.setObjectName("comboBox_task_multibox")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(62, 557, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(528, 581, 91, 71))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(0, 569, 51, 21))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(0, 644, 571, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setGeometry(QtCore.QRect(500, 569, 71, 21))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.pushButton_Upload_multibox = QtWidgets.QPushButton(self.tab)
        self.pushButton_Upload_multibox.setGeometry(QtCore.QRect(413, 604, 112, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Upload_multibox.setFont(font)
        self.pushButton_Upload_multibox.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_Upload_multibox.setObjectName("pushButton_Upload_multibox")
        self.resettable = QtWidgets.QPushButton(self.tab)
        self.resettable.setGeometry(QtCore.QRect(950, 589, 120, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.resettable.setFont(font)
        self.resettable.setObjectName("resettable")
        self.exportdata = QtWidgets.QPushButton(self.tab)
        self.exportdata.setGeometry(QtCore.QRect(620, 590, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.exportdata.setFont(font)
        self.exportdata.setObjectName("exportdata")
        self.pushButton_config_all = QtWidgets.QPushButton(self.tab)
        self.pushButton_config_all.setGeometry(QtCore.QRect(1200, 590, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_config_all.setFont(font)
        self.pushButton_config_all.setStyleSheet("background-color: rgb(241, 78, 255);")
        self.pushButton_config_all.setObjectName("pushButton_config_all")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(75)
        self.tableWidget.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(50, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(51, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(52, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(53, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(54, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(55, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(56, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(57, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(58, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(59, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(60, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(61, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(62, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(63, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(64, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(65, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(66, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(67, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(68, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(69, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(70, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(71, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(72, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(73, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(74, item)
        self.horizontalLayout_3.addWidget(self.tableWidget)
        self.Exportdata2 = QtWidgets.QPushButton(self.tab_4)
        self.Exportdata2.setObjectName("Exportdata2")
        self.horizontalLayout_3.addWidget(self.Exportdata2)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_exp.setText(_translate("MainWindow", "Experimenter Name: "))
        self.label_prj.setText(_translate("MainWindow", "Project: "))
        self.label_prj_2.setText(_translate("MainWindow", "Session"))
        self.label_data_dir.setText(_translate("MainWindow", "Data dir:"))
        self.pushButton_data_dir.setText(_translate("MainWindow", "..."))
        self.label_5.setText(_translate("MainWindow", "Variables"))
        self.pushButton_setupselect_1.setText(_translate("MainWindow", "SetUp 1"))
        self.pushButton_setupselect_2.setText(_translate("MainWindow", "SetUp 2"))
        self.pushButton_setupselect_3.setText(_translate("MainWindow", "SetUp 3"))
        self.label_2.setText(_translate("MainWindow", "Timer"))
        self.pushButton_var8.setText(_translate("MainWindow", "....."))
        self.pushButton_Start8.setText(_translate("MainWindow", "START"))
        self.pushButton_Start7.setText(_translate("MainWindow", "START"))
        self.pushButton_Start4.setText(_translate("MainWindow", "START"))
        self.label_box8.setText(_translate("MainWindow", "BOX 00"))
        self.pushButton_Start5.setText(_translate("MainWindow", "START"))
        self.pushButton_Start3.setText(_translate("MainWindow", "START"))
        self.pushButton_Stop6.setText(_translate("MainWindow", "STOP"))
        self.pushButton_connect_3.setText(_translate("MainWindow", "Connect"))
        self.label_box2.setText(_translate("MainWindow", "BOX 00"))
        self.pushButton_Stop4.setText(_translate("MainWindow", "STOP"))
        self.pushButton_connect_4.setText(_translate("MainWindow", "Connect"))
        self.pushButton_connect_6.setText(_translate("MainWindow", "Connect"))
        self.pushButton_var3.setText(_translate("MainWindow", "....."))
        self.pushButton_upload_8.setText(_translate("MainWindow", "Upload"))
        self.pushButton_config_3.setText(_translate("MainWindow", "Config"))
        self.pushButton_Stop1.setText(_translate("MainWindow", "STOP"))
        self.pushButton_Start2.setText(_translate("MainWindow", "START"))
        self.pushButton_connect_5.setText(_translate("MainWindow", "Connect"))
        self.pushButton_var6.setText(_translate("MainWindow", "....."))
        self.pushButton_config_7.setText(_translate("MainWindow", "Config"))
        self.pushButton_connect_2.setText(_translate("MainWindow", "Connect"))
        self.pushButton_config_8.setText(_translate("MainWindow", "Config"))
        self.pushButton_config_6.setText(_translate("MainWindow", "Config"))
        self.pushButton_Start1.setText(_translate("MainWindow", "START"))
        self.pushButton_Stop5.setText(_translate("MainWindow", "STOP"))
        self.pushButton_connect_8.setText(_translate("MainWindow", "Connect"))
        self.pushButton_connect_1.setText(_translate("MainWindow", "Connect"))
        self.pushButton_config_2.setText(_translate("MainWindow", "Config"))
        self.pushButton_connect_7.setText(_translate("MainWindow", "Connect"))
        self.pushButton_config_1.setText(_translate("MainWindow", "Config"))
        self.pushButton_config_4.setText(_translate("MainWindow", "Config"))
        self.pushButton_Stop2.setText(_translate("MainWindow", "STOP"))
        self.pushButton_upload_4.setText(_translate("MainWindow", "Upload"))
        self.pushButton_var7.setText(_translate("MainWindow", "....."))
        self.pushButton_upload_2.setText(_translate("MainWindow", "Upload"))
        self.pushButton_upload_6.setText(_translate("MainWindow", "Upload"))
        self.pushButton_upload_5.setText(_translate("MainWindow", "Upload"))
        self.label_box4.setText(_translate("MainWindow", "BOX 00"))
        self.label_box3.setText(_translate("MainWindow", "BOX 00"))
        self.label.setText(_translate("MainWindow", "SUBJECT ID"))
        self.label_box5.setText(_translate("MainWindow", "BOX 00"))
        self.label_box6.setText(_translate("MainWindow", "BOX 00"))
        self.label_box7.setText(_translate("MainWindow", "BOX 00"))
        self.label_box1.setText(_translate("MainWindow", "BOX 00"))
        self.label_4.setText(_translate("MainWindow", "Status"))
        self.pushButton_config_5.setText(_translate("MainWindow", "Config"))
        self.pushButton_Stop7.setText(_translate("MainWindow", "STOP"))
        self.pushButton_Upload_all.setText(_translate("MainWindow", "Upload All"))
        self.pushButton_Connect_all.setText(_translate("MainWindow", "Connect All"))
        self.pushButton_var5.setText(_translate("MainWindow", "....."))
        self.pushButton_var4.setText(_translate("MainWindow", "....."))
        self.pushButton_Stop3.setText(_translate("MainWindow", "STOP"))
        self.pushButton_upload_1.setText(_translate("MainWindow", "Upload"))
        self.label_task.setText(_translate("MainWindow", "TASK"))
        self.pushButton_upload_7.setText(_translate("MainWindow", "Upload"))
        self.label_3.setText(_translate("MainWindow", "Serial Port"))
        self.pushButton_Start6.setText(_translate("MainWindow", "START"))
        self.pushButton_var2.setText(_translate("MainWindow", "....."))
        self.pushButton_upload_3.setText(_translate("MainWindow", "Upload"))
        self.pushButton_var1.setText(_translate("MainWindow", "....."))
        self.pushButton_Stop_all.setText(_translate("MainWindow", "Stop All"))
        self.pushButton_Stop8.setText(_translate("MainWindow", "STOP"))
        self.pushButton_Start_all.setText(_translate("MainWindow", "Record All"))
        self.label_6.setText(_translate("MainWindow", "Select and Upload task for multiple Connected Boxes"))
        self.pushButton_Upload_multibox.setText(_translate("MainWindow", "Upload"))
        self.resettable.setText(_translate("MainWindow", "Reset Table"))
        self.exportdata.setText(_translate("MainWindow", "Export Data"))
        self.pushButton_config_all.setText(_translate("MainWindow", "Config All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main"))
        self.Exportdata2.setText(_translate("MainWindow", "Export DATA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
